name: geoaware
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - affine=2.4.0=pyhd8ed1ab_1
  - aom=3.9.1=hac33072_0
  - attrs=25.4.0=pyhcf101f3_1
  - backports.zstd=1.3.0=py310h69bd2ac_0
  - blosc=1.21.6=hef167b5_0
  - branca=0.8.2=pyhd8ed1ab_0
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - brotli-python=1.2.0=py310hba01987_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - contourpy=1.3.2=py310h3788b33_0
  - cycler=0.12.1=pyhcf101f3_2
  - dav1d=1.2.1=hd590300_0
  - expat=2.7.4=h7354ed3_0
  - folium=0.20.0=pyhd8ed1ab_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.61.1=py310h3406613_0
  - freetype=2.14.1=ha770c72_0
  - freexl=2.0.0=h9dce30a_2
  - fribidi=1.0.16=hb03c661_0
  - gdal=3.11.4=py310hb501871_9
  - geopandas=1.1.2=pyhd8ed1ab_0
  - geopandas-base=1.1.2=pyha770c72_0
  - geos=3.10.6=h9db6f96_0
  - geotiff=1.7.0=ha59944b_4
  - giflib=5.2.2=hd590300_0
  - graphite2=1.3.14=hecca717_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.3.0=h79d275a_1
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.11=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - json-c=0.18=h6688a6e_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py310haaf941d_2
  - krb5=1.22.2=ha1258a1_0
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h0aef613_1
  - libarchive=3.8.2=h3ec8f01_0
  - libavif=1.3.0=h316e467_3
  - libavif16=1.3.0=h316e467_3
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcblas=3.11.0=5_h0358290_openblas
  - libcurl=8.18.0=hcf29cc6_1
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.4=h7354ed3_0
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgdal-core=3.11.4=hc92985d_0
  - libgfortran=15.2.0=h69a702a_18
  - libgfortran5=15.2.0=h68bc16d_18
  - libglib=2.86.3=h8b17d9a_0
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.18=h3b78370_2
  - libkml=1.3.0=haa4a5bd_1022
  - liblapack=3.11.0=5_h47877c9_openblas
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopenjpeg=2.5.4=hee96239_1
  - libpng=1.6.55=h421ea60_0
  - libspatialite=5.1.0=h798b768_2
  - libsqlite=3.51.2=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.7.1=h029b1ac_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=hcb278e6_0
  - mapclassify=2.8.1=pyhd8ed1ab_1
  - markupsafe=3.0.3=py310h3406613_0
  - matplotlib-base=3.10.8=py310hfde16b3_0
  - minizip=4.0.7=h401b404_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - networkx=3.4.2=pyh267e887_2
  - numpy=2.2.6=py310hefbff90_0
  - openssl=3.6.1=h35e630c_1
  - packaging=25.0=py310h06a4308_1
  - pandas=2.3.3=py310h0158d43_2
  - pcre2=10.46=h1321c63_0
  - pillow=12.1.0=py310hd9fd23a_0
  - pip=26.0.1=pyhc872135_0
  - pixman=0.46.4=h54a6638_1
  - proj=9.3.1=h1d62c97_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pyogrio=0.11.1=py310h460ceab_1
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyproj=3.6.1=py310hd5c30f3_5
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.19=h6fa692b_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - rasterio=1.4.4=py310h584ab63_0
  - rav1e=0.7.1=h8fae777_3
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=pyhcf101f3_1
  - scikit-learn=1.7.2=py310h228f341_0
  - scipy=1.15.2=py310h1d65ade_0
  - setuptools=80.10.2=py310h06a4308_0
  - shapely=2.1.2=py310h3e784f6_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_1
  - sqlite=3.51.1=he0a8d7e_0
  - svt-av1=4.0.0=hecca717_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025c=he532380_0
  - unicodedata2=17.0.1=py310h7c4b9e2_0
  - uriparser=0.9.8=hac33072_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - wheel=0.46.3=py310h06a4308_0
  - xerces-c=3.3.0=ha155076_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.7=hb03c661_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - anywidget==0.9.21
      - asttokens==3.0.1
      - bqplot==0.12.45
      - cffi==2.0.0
      - comm==0.2.3
      - cryptography==46.0.5
      - decorator==5.2.1
      - earthengine-api==1.7.14
      - eerepr==0.1.2
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - future==1.0.0
      - geemap==0.37.1
      - geocoder==1.38.1
      - google-api-core==2.30.0
      - google-api-python-client==2.190.0
      - google-auth==2.48.0
      - google-auth-httplib2==0.3.0
      - google-cloud-core==2.5.0
      - google-cloud-storage==3.9.0
      - google-crc32c==1.8.0
      - google-resumable-media==2.8.0
      - googleapis-common-protos==1.72.0
      - httplib2==0.31.2
      - ipyevents==2.0.4
      - ipyfilechooser==0.6.0
      - ipyleaflet==0.20.0
      - ipython==8.38.0
      - ipywidgets==8.1.8
      - jedi==0.19.2
      - jupyter-leaflet==0.20.0
      - jupyterlab-widgets==3.0.16
      - matplotlib-inline==0.2.1
      - narwhals==2.16.0
      - parso==0.8.6
      - pexpect==4.9.0
      - plotly==6.5.2
      - prompt-toolkit==3.0.52
      - proto-plus==1.27.1
      - protobuf==6.33.5
      - psygnal==0.15.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pycparser==3.0
      - pygments==2.19.2
      - pyperclip==1.11.0
      - pyshp==3.0.3
      - python-box==7.3.2
      - ratelim==0.1.6
      - rsa==4.9.1
      - scooby==0.11.0
      - stack-data==0.6.3
      - traitlets==5.14.3
      - traittypes==0.2.3
      - typing-extensions==4.15.0
      - uritemplate==4.2.0
      - wcwidth==0.6.0
      - widgetsnbextension==4.0.15
prefix: /home/agnis/miniconda3/envs/geoaware
